-- Get the id and description of crime scene from crime_scene_reports table by date and place
--SELECT description FROM crime_scene_reports WHERE day=28 AND month=7 AND year=2020 AND street="Chamberlin Street";

-- According to the description of the selected crime scene, there are three witnesses and each of their transcripts mentions the courthouse.
-- Get the three witnesses' names and their transcripts from interviews table by the crime's date and mentions of the courthouse
SELECT name, transcript FROM interviews WHERE day=28 AND month=7 AND year=2020 AND transcript LIKE "%courthouse%";

--SELECT license_plate FROM courthouse_security_logs WHERE day=28 AND month=7 AND year=2020 AND activity="exit";

-- According  to Raymond and his transcript, we can search phone calls, flights, airports, and passengers to find the thief
-- Get the list of callers and receivers from phone_calls table by date and duration
--SELECT caller, receiver FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60;

-- From phone numbers of callers and receivers we can get the name and passport numbers of callers and receivers
-- Before getting the names and passport numbers, we need to find the potential list of airports and flights
--SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5;

-- We can get the list of name and passport numbers of callers and receivers
-- List of names and passport numbers of callers
--SELECT name, passport_number FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60);
-- List of names and passport numbers of receivers
--SELECT name, passport_number FROM people WHERE phone_number IN (SELECT receiver FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60);

-- Get the list of passengers using the list of passport numbers and the flight id
--SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5);
SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 1)) AND license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day=28 AND month=7 AND year=2020 AND activity="exit");
SELECT phone_number, passport_number, license_plate FROM people WHERE name="Roger";
SELECT phone_number, passport_number, license_plate FROM people WHERE name="Madison";
SELECT phone_number, passport_number, license_plate FROM people WHERE name="Evelyn";
SELECT phone_number, passport_number, license_plate FROM people WHERE name="Ernest";

--SELECT flight_id FROM passengers WHERE passport_number = (SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=28 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5))));
--SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=28 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)));
--SELECT destination_airport_id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND id = (SELECT flight_id FROM passengers WHERE passport_number = (SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)))));

SELECT city FROM airports WHERE id = (SELECT destination_airport_id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND id = (SELECT flight_id FROM passengers WHERE passport_number = (SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5))))));
--SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND destination_airport_id = (SELECT destination_airport_id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND id = (SELECT flight_id FROM passengers WHERE passport_number = (SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)))))) ORDER BY hour;
--SELECT passport_number FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND destination_airport_id = (SELECT destination_airport_id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id = (SELECT id FROM airports WHERE city="Fiftyville") AND id = (SELECT flight_id FROM passengers WHERE passport_number = (SELECT passport_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)))))) ORDER BY hour);

SELECT account_number FROM bank_accounts WHERE person_id IN (SELECT id FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 1)) AND license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day=28 AND month=7 AND year=2020 AND activity="exit"));
SELECT account_number FROM atm_transactions WHERE account_number IN (SELECT account_number FROM bank_accounts WHERE person_id IN (SELECT id FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=29 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 1)) AND license_plate IN (SELECT license_plate FROM courthouse_security_logs WHERE day=28 AND month=7 AND year=2020 AND activity="exit")));

--SELECT phone_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=28 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)));

--SELECT receiver FROM phone_calls WHERE caller = (SELECT phone_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=28 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)))) AND day=28 AND month=7 AND year=2020 AND duration < 60;

--SELECT name FROM people WHERE phone_number = (SELECT receiver FROM phone_calls WHERE caller = (SELECT phone_number FROM people WHERE name = (SELECT name FROM people WHERE phone_number IN (SELECT caller FROM phone_calls WHERE day=28 AND month=7 AND year=2020 AND duration < 60) AND passport_number IN (SELECT passport_number FROM passengers WHERE flight_id IN (SELECT id FROM flights WHERE day=28 AND month=7 AND year=2020 AND origin_airport_id=(SELECT id FROM airports WHERE city="Fiftyville") ORDER BY hour LIMIT 5)))) AND day=28 AND month=7 AND year=2020 AND duration < 60);

